# Site settings
title: Baptiste Meurant
email: baptiste.meurant@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bmeurant.github.io" # the base hostname & protocol for your site
description: Software craftsman, full stack developer, architect, open source enthousiast
twitter_username: bmeurant
github_username:  bmeurant

# Build settings
markdown: redcarpet
redcarpet:
    extensions: [with_toc_data]
highlighter: pygment
exclude: [package.json, bower.json, node_modules, bower_components, Gemfile, Gemfile.lock, less, Gruntfile.js]
permalink: /post/:year/:month/:day/:title/
